@startuml
skinparam componentStyle uml2
skinparam monochrome true
skinparam shadowing false
skinparam classAttributeIconSize 0


title Motor Control Loop

frame "Firmware" {
    [Target Speed] as setpoint
    [PI Controller] as pi
    [PWM Generation] as pwm
    [Stall Detection] as stall
    [Rangiermodus] as rangier
}

frame "Hardware" {
    [Motor Driver] as driver
    [DC Motor] as motor#Salmon
    [Analog-to-Digital\nConverter] as adc
}

frame "Signal Processing" {
    [EMA Filter] as ema
    [Kalman Filter] as kalman
    [Pulse Counter] as counter
}

setpoint -> pi : speed_setpoint_pps
setpoint -> rangier
setpoint -> stall

rangier -> pi : adjusts gains

pi -> pwm : pwm_duty_cycle
pwm -> driver
driver --> motor
motor --> adc : back_EMF_voltage

adc -> ema : raw_bemf_adc
ema -> kalman : smoothed_bemf
kalman -> counter : kalman_filtered_bemf
counter --> pi : measured_speed_pps
counter --> stall : measured_speed_pps

stall -> pi : sets target_speed to 0
@enduml
